DayHabit.destroy_all
Note.destroy_all
Habit.destroy_all
Day.destroy_all
User.destroy_all

#user seeds
billy = User.create(email: 'billy@billy.com', username: 'bott18', password: 'Kerokero18' )
schyler = User.create(email: 'schyler@schyler.com', username: 'shosler16', password: 'Kerokero16' )

#day seeds
b_d1 = Day.create(date: Date.new(2020,11,1), mood_score: 3, sleep_hours: 5, user: billy)
b_d2 = Day.create(date: Date.new(2020,11,2), mood_score: 4, sleep_hours: 6, user: billy)
b_d3 = Day.create(date: Date.new(2020,11,3), mood_score: 5, sleep_hours: 7, user: billy)
b_d4 = Day.create(date: Date.new(2020,11,4), mood_score: 6, sleep_hours: 8, user: billy)
b_d5 = Day.create(date: Date.new(2020,11,5), mood_score: 7, sleep_hours: 9, user: billy)
b_d6 = Day.create(date: Date.new(2020,11,6), mood_score: 8, sleep_hours: 4, user: billy)
b_d7 = Day.create(date: Date.new(2020,11,7), mood_score: 9, sleep_hours: 5, user: billy)
b_d8 = Day.create(date: Date.new(2020,11,8), mood_score: 10, sleep_hours: 7, user: billy)
b_d9 = Day.create(date: Date.new(2020,11,9), mood_score: 1, sleep_hours: 8, user: billy)
b_d10 = Day.create(date: Date.new(2020,11,10), mood_score: 2, sleep_hours: 9, user: billy)
b_d11 = Day.create(date: Date.new(2020,11,11), mood_score: 3, sleep_hours: 10, user: billy)
b_d12 = Day.create(date: Date.new(2020,11,12), mood_score: 4, sleep_hours: 8, user: billy)
b_d13 = Day.create(date: Date.new(2020,11,13), mood_score: 5, sleep_hours: 7, user: billy)
b_d14 = Day.create(date: Date.new(2020,11,14), mood_score: 6, sleep_hours: 5, user: billy)
b_d15 = Day.create(date: Date.new(2020,11,15), mood_score: 7, sleep_hours: 4, user: billy)
b_d16 = Day.create(date: Date.new(2020,11,16), mood_score: 8, sleep_hours: 7, user: billy)
b_d17 = Day.create(date: Date.new(2020,11,17), mood_score: 9, sleep_hours: 8, user: billy)
b_d18 = Day.create(date: Date.new(2020,11,18), mood_score: 10, sleep_hours: 9, user: billy)
b_d19 = Day.create(date: Date.new(2020,11,19), mood_score: 3, sleep_hours: 10, user: billy)
b_d20 = Day.create(date: Date.new(2020,11,20), mood_score: 4, sleep_hours: 4, user: billy)
b_d21 = Day.create(date: Date.new(2020,11,21), mood_score: 5, sleep_hours: 6, user: billy)
b_d22 = Day.create(date: Date.new(2020,11,22), mood_score: 6, sleep_hours: 7, user: billy)
b_d23 = Day.create(date: Date.new(2020,11,23), mood_score: 7, sleep_hours: 8, user: billy)
b_d24 = Day.create(date: Date.new(2020,11,24), mood_score: 8, sleep_hours: 4, user: billy)
b_d25 = Day.create(date: Date.new(2020,11,25), mood_score: 9, sleep_hours: 8, user: billy)
b_d26 = Day.create(date: Date.new(2020,11,26), mood_score: 10, sleep_hours: 8, user: billy)
b_d27 = Day.create(date: Date.new(2020,11,27), mood_score: 3, sleep_hours: 8, user: billy)
b_d28 = Day.create(date: Date.new(2020,11,28), mood_score: 4, sleep_hours: 8, user: billy)
b_d29 = Day.create(date: Date.new(2020,11,29), mood_score: 1, sleep_hours: 5, user: billy)
b_d30 = Day.create(date: Date.new(2020,11,30), mood_score: 2, sleep_hours: 6, user: billy)
b_d31 = Day.create(date: Date.new(2020,12,13), mood_score: 2, sleep_hours: 6, user: billy)

#note seeds
b_d1_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_d1)
b_d1_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_d1)
b_d1_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_d1)
b_d2_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_d2)
b_d2_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_d2)
b_d2_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_d2)
b_d3_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_d3)
b_d3_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_d3)
b_d3_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_d3)
b_d4_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_d4)
b_d4_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_d4)
b_d4_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_d4)
b_d5_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_d5)
b_d5_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_d5)
b_d5_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_d5)
b_d6_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_d6)
b_d6_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_d6)
b_d6_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_d6)
b_d7_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_d7)
b_d7_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_d7)
b_d7_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_d7)


#habit seeds
b_h1 = Habit.create(title: "Exercise", archived: false, user: billy)
b_h2 = Habit.create(title: "Meditation", archived: false, user: billy)
b_h3 = Habit.create(title: "Practice Piano", archived: false, user: billy)
b_h4 = Habit.create(title: "Floss", archived: true, user: billy)


#day_habit seeds
b_d1_h1 = DayHabit.create(day_id: b_d1.id, habit_id: b_h1.id)
b_d1_h2 = DayHabit.create(day_id: b_d1.id, habit_id: b_h2.id)
b_d2_h1 = DayHabit.create(day_id: b_d2.id, habit_id: b_h1.id)
b_d2_h2 = DayHabit.create(day_id: b_d2.id, habit_id: b_h2.id)
b_d2_h3 = DayHabit.create(day_id: b_d2.id, habit_id: b_h3.id)
b_d3_h2 = DayHabit.create(day_id: b_d3.id, habit_id: b_h1.id)
b_d3_h2 = DayHabit.create(day_id: b_d3.id, habit_id: b_h2.id)
b_d3_h3 = DayHabit.create(day_id: b_d3.id, habit_id: b_h3.id)
b_d3_h4 = DayHabit.create(day_id: b_d3.id, habit_id: b_h4.id)
b_d4_h2 = DayHabit.create(day_id: b_d4.id, habit_id: b_h1.id)
b_d4_h2 = DayHabit.create(day_id: b_d4.id, habit_id: b_h2.id)
b_d4_h3 = DayHabit.create(day_id: b_d4.id, habit_id: b_h3.id)
b_d4_h4 = DayHabit.create(day_id: b_d4.id, habit_id: b_h4.id)
b_d5_h2 = DayHabit.create(day_id: b_d5.id, habit_id: b_h2.id)
b_d5_h3 = DayHabit.create(day_id: b_d5.id, habit_id: b_h3.id)
b_d6_h2 = DayHabit.create(day_id: b_d6.id, habit_id: b_h2.id)
b_d6_h3 = DayHabit.create(day_id: b_d6.id, habit_id: b_h3.id)
b_d7_h1 = DayHabit.create(day_id: b_d7.id, habit_id: b_h1.id)
b_d7_h2 = DayHabit.create(day_id: b_d7.id, habit_id: b_h2.id)