DayHabit.destroy_all
Note.destroy_all
Habit.destroy_all
Day.destroy_all
User.destroy_all

#user seeds
billy = User.create(email: 'billy@billy.com', username: 'bott18', password: 'Kerokero18' )
schyler = User.create(email: 'schyler@schyler.com', username: 'shosler16', password: 'Kerokero16' )

#day seeds
b_nd1 = Day.create(date: Date.new(2020,11,1), mood_score: 3, sleep_hours: 5, user: billy)
b_nd2 = Day.create(date: Date.new(2020,11,2), mood_score: 4, sleep_hours: 6, user: billy)
b_nd3 = Day.create(date: Date.new(2020,11,3), mood_score: 5, sleep_hours: 7, user: billy)
b_nd4 = Day.create(date: Date.new(2020,11,4), mood_score: 6, sleep_hours: 8, user: billy)
b_nd5 = Day.create(date: Date.new(2020,11,5), mood_score: 7, sleep_hours: 9, user: billy)
b_nd6 = Day.create(date: Date.new(2020,11,6), mood_score: 8, sleep_hours: 4, user: billy)
b_nd7 = Day.create(date: Date.new(2020,11,7), mood_score: 9, sleep_hours: 5, user: billy)
b_nd8 = Day.create(date: Date.new(2020,11,8), mood_score: 10, sleep_hours: 7, user: billy)
b_nd9 = Day.create(date: Date.new(2020,11,9), mood_score: 1, sleep_hours: 8, user: billy)
b_nd10 = Day.create(date: Date.new(2020,11,10), mood_score: 2, sleep_hours: 9, user: billy)
b_nd11 = Day.create(date: Date.new(2020,11,11), mood_score: 3, sleep_hours: 10, user: billy)
b_nd12 = Day.create(date: Date.new(2020,11,12), mood_score: 4, sleep_hours: 8, user: billy)
b_nd13 = Day.create(date: Date.new(2020,11,13), mood_score: 5, sleep_hours: 7, user: billy)
b_nd14 = Day.create(date: Date.new(2020,11,14), mood_score: 6, sleep_hours: 5, user: billy)
b_nd15 = Day.create(date: Date.new(2020,11,15), mood_score: 7, sleep_hours: 4, user: billy)
b_nd16 = Day.create(date: Date.new(2020,11,16), mood_score: 8, sleep_hours: 7, user: billy)
b_nd17 = Day.create(date: Date.new(2020,11,17), mood_score: 9, sleep_hours: 8, user: billy)
b_nd18 = Day.create(date: Date.new(2020,11,18), mood_score: 10, sleep_hours: 9, user: billy)
b_nd19 = Day.create(date: Date.new(2020,11,19), mood_score: 3, sleep_hours: 10, user: billy)
b_nd20 = Day.create(date: Date.new(2020,11,20), mood_score: 4, sleep_hours: 4, user: billy)
b_nd21 = Day.create(date: Date.new(2020,11,21), mood_score: 5, sleep_hours: 6, user: billy)
b_nd22 = Day.create(date: Date.new(2020,11,22), mood_score: 6, sleep_hours: 7, user: billy)
b_nd23 = Day.create(date: Date.new(2020,11,23), mood_score: 7, sleep_hours: 8, user: billy)
b_nd24 = Day.create(date: Date.new(2020,11,24), mood_score: 8, sleep_hours: 4, user: billy)
b_nd25 = Day.create(date: Date.new(2020,11,25), mood_score: 9, sleep_hours: 8, user: billy)
b_nd26 = Day.create(date: Date.new(2020,11,26), mood_score: 10, sleep_hours: 8, user: billy)
b_nd27 = Day.create(date: Date.new(2020,11,27), mood_score: 3, sleep_hours: 8, user: billy)
b_nd28 = Day.create(date: Date.new(2020,11,28), mood_score: 4, sleep_hours: 8, user: billy)
b_nd29 = Day.create(date: Date.new(2020,11,29), mood_score: 1, sleep_hours: 5, user: billy)
b_nd30 = Day.create(date: Date.new(2020,11,30), mood_score: 2, sleep_hours: 6, user: billy)

b_dd1 = Day.create(date: Date.new(2020,12,1), mood_score: 3, sleep_hours: 5, user: billy)
b_dd2 = Day.create(date: Date.new(2020,12,2), mood_score: 4, sleep_hours: 6, user: billy)
b_dd3 = Day.create(date: Date.new(2020,12,3), mood_score: 5, sleep_hours: 7, user: billy)
b_dd4 = Day.create(date: Date.new(2020,12,4), mood_score: 6, sleep_hours: 8, user: billy)
b_dd5 = Day.create(date: Date.new(2020,12,5), mood_score: 7, sleep_hours: 9, user: billy)
b_dd6 = Day.create(date: Date.new(2020,12,6), mood_score: 8, sleep_hours: 4, user: billy)
b_dd7 = Day.create(date: Date.new(2020,12,7), mood_score: 9, sleep_hours: 5, user: billy)
b_dd8 = Day.create(date: Date.new(2020,12,8), mood_score: 10, sleep_hours: 7, user: billy)
b_dd9 = Day.create(date: Date.new(2020,12,9), mood_score: 1, sleep_hours: 8, user: billy)
b_dd10 = Day.create(date: Date.new(2020,12,10), mood_score: 2, sleep_hours: 9, user: billy)
b_dd11 = Day.create(date: Date.new(2020,12,11), mood_score: 3, sleep_hours: 10, user: billy)
b_dd12 = Day.create(date: Date.new(2020,12,12), mood_score: 4, sleep_hours: 8, user: billy)
b_dd13 = Day.create(date: Date.new(2020,12,13), mood_score: 5, sleep_hours: 7, user: billy)
b_dd14 = Day.create(date: Date.new(2020,12,14), mood_score: 6, sleep_hours: 5, user: billy)
b_dd15 = Day.create(date: Date.new(2020,12,15), mood_score: 7, sleep_hours: 4, user: billy)
b_dd16 = Day.create(date: Date.new(2020,12,16), mood_score: 8, sleep_hours: 7, user: billy)
b_dd17 = Day.create(date: Date.new(2020,12,17), mood_score: 9, sleep_hours: 8, user: billy)
# b_dd18 = Day.create(date: Date.new(2020,12,18), mood_score: 10, sleep_hours: 9, user: billy)
# b_dd19 = Day.create(date: Date.new(2020,12,19), mood_score: 3, sleep_hours: 10, user: billy)
# b_dd20 = Day.create(date: Date.new(2020,12,20), mood_score: 4, sleep_hours: 4, user: billy)
# b_dd21 = Day.create(date: Date.new(2020,12,21), mood_score: 5, sleep_hours: 6, user: billy)
# b_dd22 = Day.create(date: Date.new(2020,12,22), mood_score: 6, sleep_hours: 7, user: billy)
# b_dd23 = Day.create(date: Date.new(2020,12,23), mood_score: 7, sleep_hours: 8, user: billy)
# b_dd24 = Day.create(date: Date.new(2020,12,24), mood_score: 8, sleep_hours: 4, user: billy)
# b_dd25 = Day.create(date: Date.new(2020,12,25), mood_score: 9, sleep_hours: 8, user: billy)
# b_dd26 = Day.create(date: Date.new(2020,12,26), mood_score: 10, sleep_hours: 8, user: billy)
# b_dd27 = Day.create(date: Date.new(2020,12,27), mood_score: 3, sleep_hours: 8, user: billy)
# b_dd28 = Day.create(date: Date.new(2020,12,28), mood_score: 4, sleep_hours: 8, user: billy)
# b_dd29 = Day.create(date: Date.new(2020,12,29), mood_score: 1, sleep_hours: 5, user: billy)
# b_dd30 = Day.create(date: Date.new(2020,12,30), mood_score: 2, sleep_hours: 6, user: billy)
# b_dd31 = Day.create(date: Date.new(2020,12,31), mood_score: 2, sleep_hours: 6, user: billy)

#note seeds
b_nd1_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_nd1)
b_nd1_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_nd1)
b_nd1_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_nd1)
b_nd2_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_nd2)
b_nd2_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_nd2)
b_nd2_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_nd2)
b_nd3_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_nd3)
b_nd3_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_nd3)
b_nd3_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_nd3)
b_nd4_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_nd4)
b_nd4_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_nd4)
b_nd4_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_nd4)
b_nd5_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_nd5)
b_nd5_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_nd5)
b_nd5_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_nd5)
b_nd6_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_nd6)
b_nd6_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_nd6)
b_nd6_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_nd6)
b_nd7_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_nd7)
b_nd7_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_nd7)
b_nd7_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_nd7)

b_dd1_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_dd1)
b_dd1_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_dd1)
b_dd1_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_dd1)
b_dd2_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_dd2)
b_dd2_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_dd2)
b_dd2_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_dd2)
b_dd3_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_dd3)
b_dd3_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_dd3)
b_dd3_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_dd3)
b_dd4_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_dd4)
b_dd4_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_dd4)
b_dd4_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_dd4)
b_dd5_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_dd5)
b_dd5_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_dd5)
b_dd5_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_dd5)
b_dd6_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_dd6)
b_dd6_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_dd6)
b_dd6_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_dd6)
b_dd7_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_dd7)
b_dd7_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_dd7)
b_dd7_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_dd7)

b_dd14_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_dd14)
b_dd14_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_dd14)
b_dd14_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_dd14)
b_dd15_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_dd15)
b_dd15_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_dd15)
b_dd15_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_dd15)
b_dd16_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_dd16)
b_dd16_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_dd16)
b_dd16_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_dd16)
b_dd17_n1 = Note.create(note: "lorem ipsum1", note_type: "Thought", important: false, day: b_dd17)
b_dd17_n2 = Note.create(note: "lorem ipsum2", note_type: "Thought", important: true, day: b_dd17)
b_dd17_n3 = Note.create(note: "lorem ipsum3", note_type: "Event", important: false, day: b_dd17)


#habit seeds
b_h1 = Habit.create(title: "Exercise", archived: false, user: billy)
b_h2 = Habit.create(title: "Meditation", archived: false, user: billy)
b_h3 = Habit.create(title: "Practice Piano", archived: false, user: billy)
b_h4 = Habit.create(title: "Floss", archived: true, user: billy)


#day_habit seeds
b_dd1_h1 = DayHabit.create(day_id: b_dd1.id, habit_id: b_h1.id)
b_dd1_h2 = DayHabit.create(day_id: b_dd1.id, habit_id: b_h2.id)
b_dd2_h1 = DayHabit.create(day_id: b_dd2.id, habit_id: b_h1.id)
b_dd2_h2 = DayHabit.create(day_id: b_dd2.id, habit_id: b_h2.id)
b_dd2_h3 = DayHabit.create(day_id: b_dd2.id, habit_id: b_h3.id)
b_dd3_h2 = DayHabit.create(day_id: b_dd3.id, habit_id: b_h1.id)
b_dd3_h2 = DayHabit.create(day_id: b_dd3.id, habit_id: b_h2.id)
b_dd3_h3 = DayHabit.create(day_id: b_dd3.id, habit_id: b_h3.id)
b_dd3_h4 = DayHabit.create(day_id: b_dd3.id, habit_id: b_h4.id)
b_dd4_h2 = DayHabit.create(day_id: b_dd4.id, habit_id: b_h1.id)
b_dd4_h2 = DayHabit.create(day_id: b_dd4.id, habit_id: b_h2.id)
b_dd4_h3 = DayHabit.create(day_id: b_dd4.id, habit_id: b_h3.id)
b_dd4_h4 = DayHabit.create(day_id: b_dd4.id, habit_id: b_h4.id)
b_dd5_h2 = DayHabit.create(day_id: b_dd5.id, habit_id: b_h2.id)
b_dd5_h3 = DayHabit.create(day_id: b_dd5.id, habit_id: b_h3.id)
b_dd6_h2 = DayHabit.create(day_id: b_dd6.id, habit_id: b_h2.id)
b_dd6_h3 = DayHabit.create(day_id: b_dd6.id, habit_id: b_h3.id)
b_dd7_h1 = DayHabit.create(day_id: b_dd7.id, habit_id: b_h1.id)
b_dd7_h2 = DayHabit.create(day_id: b_dd7.id, habit_id: b_h2.id)